/****************************************************************************
**
** Copyright (C) 2016 The Qt Company Ltd.
** Contact: https://www.qt.io/licensing/
**
** This file is part of the autotests of the Qt Toolkit.
**
** $QT_BEGIN_LICENSE:GPL-EXCEPT$
** Commercial License Usage
** Licensees holding valid commercial Qt licenses may use this file in
** accordance with the commercial license agreement provided with the
** Software or, alternatively, in accordance with the terms contained in
** a written agreement between you and The Qt Company. For licensing terms
** and conditions see https://www.qt.io/terms-conditions. For further
** information use the contact form at https://www.qt.io/contact-us.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3 as published by the Free Software
** Foundation with exceptions as appearing in the file LICENSE.GPL3-EXCEPT
** included in the packaging of this file. Please review the following
** information to ensure the GNU General Public License requirements will
** be met: https://www.gnu.org/licenses/gpl-3.0.html.
**
** $QT_END_LICENSE$
**
****************************************************************************/

#include <QtDebug>

#include <private/qacceltreeresourceloader_p.h>
#include <private/qnetworkaccessdelegator_p.h>

#include "Global.h"
#include "TestBaseLine.h"
#include "TestGroup.h"

#include "XSDTestSuiteHandler.h"
#include "XSDTSTestCase.h"

using namespace QPatternistSDK;

extern QNetworkAccessManager s_networkManager;

XSDTestSuiteHandler::XSDTestSuiteHandler(const QUrl &catalogFile) : m_ts(0)
                                                                    , m_catalogFile(catalogFile)
                                                                    , m_inSchemaTest(false)
                                                                    , m_inInstanceTest(false)
                                                                    , m_inTestGroup(false)
                                                                    , m_inDescription(false)
                                                                    , m_schemaBlacklisted(false)
                                                                    , m_counter(0)
{
    Q_ASSERT(!m_catalogFile.isRelative());
    m_ts = new TestSuite();
    m_topLevelGroup = new TestGroup(m_ts);
    m_topLevelGroup->setTitle("XML Schema Test Suite");
    m_ts->appendChild(m_topLevelGroup);

    // exclude these test cases, as they break our current state machine
    m_blackList << QLatin1StringView("addB099")
                << QLatin1StringView("addB118")
                << QLatin1StringView("elemJ003")
                << QLatin1StringView("elemJ011")
                << QLatin1StringView("elemZ004")
                << QLatin1StringView("elemZ020")
                << QLatin1StringView("groupH021v")
                << QLatin1StringView("groupJ009v")
                << QLatin1StringView("name00101m2")
                << QLatin1StringView("schL5")
                << QLatin1StringView("ste110")
                << QLatin1StringView("stZ007")
                << QLatin1StringView("stZ047")
                << QLatin1StringView("stZ055")
                << QLatin1StringView("addB049")
                << QLatin1StringView("addB068")
                << QLatin1StringView("addB078")
                << QLatin1StringView("addB078A")
                << QLatin1StringView("addB078B")
                << QLatin1StringView("addB167")
                << QLatin1StringView("addB191")
                << QLatin1StringView("isDefault060_2")
                << QLatin1StringView("isDefault069")
                << QLatin1StringView("annotB025")
                << QLatin1StringView("base64Binary_enumeration003_1321")
                << QLatin1StringView("anyURI_a001_1336")
                << QLatin1StringView("anyURI_a001_1336")
                << QLatin1StringView("anyURI_a003_1338")
                << QLatin1StringView("anyURI_a004_1339")
                << QLatin1StringView("anyURI_b004_1354")
                << QLatin1StringView("anyURI_b004_1354")
                << QLatin1StringView("anyURI_b006_1356")
                << QLatin1StringView("QName_length001_1357")
                << QLatin1StringView("QName_length003_1359")
                << QLatin1StringView("QName_minLength003_1362")
                << QLatin1StringView("QName_maxLength001_1364")
                << QLatin1StringView("NOTATION_length001_1372")
                << QLatin1StringView("NOTATION_length003_1374")
                << QLatin1StringView("NOTATION_minLength003_1377")
                << QLatin1StringView("NOTATION_maxLength001_1379")
                << QLatin1StringView("hexBinary003_2069")
                << QLatin1StringView("QName009_2092")
                << QLatin1StringView("dtZ107447_a_2245")
                << QLatin1StringView("elemE001")
                << QLatin1StringView("elemE002")
                << QLatin1StringView("elemE003")
                << QLatin1StringView("elemE004")
                << QLatin1StringView("elemE005")
                << QLatin1StringView("elemT026")
                << QLatin1StringView("elemT027")
                << QLatin1StringView("elemT028")
                << QLatin1StringView("elemT029")
                << QLatin1StringView("elemT054")
                << QLatin1StringView("elemT055")
                << QLatin1StringView("elemT056")
                << QLatin1StringView("elemT057")
                << QLatin1StringView("elemZ006")
                << QLatin1StringView("elemZ007")
                << QLatin1StringView("elemZ026")
                << QLatin1StringView("elemZ027_c")
                << QLatin1StringView("elemZ028c")
                << QLatin1StringView("elemZ028d")
                << QLatin1StringView("elemZ028f1")
                << QLatin1StringView("elemZ028f1")
                << QLatin1StringView("elemZ028f2")
                << QLatin1StringView("elemZ028f2")
                << QLatin1StringView("elemZ028f3")
                << QLatin1StringView("elemZ028f3")
                << QLatin1StringView("elemZ031")
                << QLatin1StringView("errF001")
                << QLatin1StringView("idC019")
                << QLatin1StringView("idL100")
                << QLatin1StringView("idZ011")
                << QLatin1StringView("idZ015")
                << QLatin1StringView("mgO013")
                << QLatin1StringView("particlesA012")
                << QLatin1StringView("particlesA013")
                << QLatin1StringView("particlesA014")
                << QLatin1StringView("particlesA015")
                << QLatin1StringView("particlesHa161")
                << QLatin1StringView("particlesHb008")
                << QLatin1StringView("particlesHb011")
                << QLatin1StringView("particlesIe003")
                << QLatin1StringView("particlesIg003")
                << QLatin1StringView("particlesIg004")
                << QLatin1StringView("particlesJb003")
                << QLatin1StringView("particlesJd003")
                << QLatin1StringView("particlesJf003")
                << QLatin1StringView("particlesJk003")
                << QLatin1StringView("particlesOb001")
                << QLatin1StringView("particlesOb002")
                << QLatin1StringView("particlesOb004")
                << QLatin1StringView("particlesOb008")
                << QLatin1StringView("particlesOb009")
                << QLatin1StringView("particlesOb013")
                << QLatin1StringView("particlesOb018")
                << QLatin1StringView("particlesQ005")
                << QLatin1StringView("particlesS002")
                << QLatin1StringView("particlesT002")
                << QLatin1StringView("particlesT009")
                << QLatin1StringView("particlesT014")
                << QLatin1StringView("particlesV001")
                << QLatin1StringView("particlesV002")
                << QLatin1StringView("particlesV020")
                << QLatin1StringView("particlesZ001")
                << QLatin1StringView("particlesZ005")
                << QLatin1StringView("particlesZ007")
                << QLatin1StringView("particlesZ023")
                << QLatin1StringView("particlesZ024")
                << QLatin1StringView("particlesZ026")
                << QLatin1StringView("particlesZ028")
                << QLatin1StringView("particlesZ033_c")
                << QLatin1StringView("particlesZ033_d")
                << QLatin1StringView("particlesZ033_e")
                << QLatin1StringView("particlesZ033_f")
                << QLatin1StringView("particlesZ033_g")
                << QLatin1StringView("particlesZ034_a1")
                << QLatin1StringView("particlesZ034_a2")
                << QLatin1StringView("particlesZ034_a3")
                << QLatin1StringView("particlesZ034_b")
                << QLatin1StringView("particlesZ035_a")
                << QLatin1StringView("particlesZ035_b")
                << QLatin1StringView("particlesZ036_a")
                << QLatin1StringView("particlesZ036_b1")
                << QLatin1StringView("particlesZ036_b2")
                << QLatin1StringView("particlesZ036_c")
/*
                << QLatin1StringView("reC65")
                << QLatin1StringView("reC66")
                << QLatin1StringView("reC67")
                << QLatin1StringView("reC68")
                << QLatin1StringView("reF58")
                << QLatin1StringView("reG50")
                << QLatin1StringView("reJ11")
                << QLatin1StringView("reJ13")
                << QLatin1StringView("reJ19")
                << QLatin1StringView("reJ21")
                << QLatin1StringView("reJ23")
                << QLatin1StringView("reJ25")
                << QLatin1StringView("reJ29")
                << QLatin1StringView("reJ31")
                << QLatin1StringView("reJ33")
                << QLatin1StringView("reJ35")
                << QLatin1StringView("reJ61")
                << QLatin1StringView("reJ69")
                << QLatin1StringView("reJ75")
                << QLatin1StringView("reJ77")
                << QLatin1StringView("reL98")
                << QLatin1StringView("reL99")
                << QLatin1StringView("reM98")
                << QLatin1StringView("reN99")
                << QLatin1StringView("reS21")
                << QLatin1StringView("reS42")
                << QLatin1StringView("reT63")
                << QLatin1StringView("reT84")
                << QLatin1StringView("reDG2")
                << QLatin1StringView("RegexTest_9")
                << QLatin1StringView("RegexTest_11")
                << QLatin1StringView("RegexTest_14")
                << QLatin1StringView("RegexTest_15")
                << QLatin1StringView("RegexTest_16")
                << QLatin1StringView("RegexTest_17")
                << QLatin1StringView("RegexTest_23")
                << QLatin1StringView("RegexTest_24")
                << QLatin1StringView("RegexTest_25")
                << QLatin1StringView("RegexTest_26")
                << QLatin1StringView("RegexTest_27")
                << QLatin1StringView("RegexTest_28")
                << QLatin1StringView("RegexTest_30")
                << QLatin1StringView("RegexTest_30")
                << QLatin1StringView("RegexTest_33")
                << QLatin1StringView("RegexTest_34")
                << QLatin1StringView("RegexTest_34")
                << QLatin1StringView("RegexTest_43")
                << QLatin1StringView("RegexTest_44")
                << QLatin1StringView("RegexTest_45")
                << QLatin1StringView("RegexTest_46")
                << QLatin1StringView("RegexTest_47")
                << QLatin1StringView("RegexTest_48")
                << QLatin1StringView("RegexTest_49")
                << QLatin1StringView("RegexTest_50")
                << QLatin1StringView("RegexTest_51")
                << QLatin1StringView("RegexTest_52")
                << QLatin1StringView("RegexTest_53")
                << QLatin1StringView("RegexTest_54")
                << QLatin1StringView("RegexTest_55")
                << QLatin1StringView("RegexTest_56")
                << QLatin1StringView("RegexTest_57")
                << QLatin1StringView("RegexTest_57")
                << QLatin1StringView("RegexTest_58")
                << QLatin1StringView("RegexTest_58")
                << QLatin1StringView("RegexTest_65")
                << QLatin1StringView("RegexTest_113")
                << QLatin1StringView("RegexTest_116")
                << QLatin1StringView("RegexTest_119")
                << QLatin1StringView("RegexTest_120")
                << QLatin1StringView("RegexTest_121")
                << QLatin1StringView("RegexTest_141")
                << QLatin1StringView("RegexTest_142")
                << QLatin1StringView("RegexTest_143")
                << QLatin1StringView("RegexTest_145")
                << QLatin1StringView("RegexTest_146")
                << QLatin1StringView("RegexTest_147")
                << QLatin1StringView("RegexTest_148")
                << QLatin1StringView("RegexTest_149")
                << QLatin1StringView("RegexTest_150")
                << QLatin1StringView("RegexTest_151")
                << QLatin1StringView("RegexTest_152")
                << QLatin1StringView("RegexTest_154")
                << QLatin1StringView("RegexTest_155")
                << QLatin1StringView("RegexTest_156")
                << QLatin1StringView("RegexTest_157")
                << QLatin1StringView("RegexTest_158")
                << QLatin1StringView("RegexTest_163")
                << QLatin1StringView("RegexTest_164")
                << QLatin1StringView("RegexTest_165")
                << QLatin1StringView("RegexTest_166")
                << QLatin1StringView("RegexTest_167")
                << QLatin1StringView("RegexTest_168")
                << QLatin1StringView("RegexTest_169")
                << QLatin1StringView("RegexTest_170")
                << QLatin1StringView("RegexTest_171")
                << QLatin1StringView("RegexTest_172")
                << QLatin1StringView("RegexTest_173")
                << QLatin1StringView("RegexTest_174")
                << QLatin1StringView("RegexTest_178")
                << QLatin1StringView("RegexTest_194")
                << QLatin1StringView("RegexTest_194")
                << QLatin1StringView("RegexTest_195")
                << QLatin1StringView("RegexTest_195")
                << QLatin1StringView("RegexTest_196")
                << QLatin1StringView("RegexTest_196")
                << QLatin1StringView("RegexTest_197")
                << QLatin1StringView("RegexTest_198")
                << QLatin1StringView("RegexTest_199")
                << QLatin1StringView("RegexTest_200")
                << QLatin1StringView("RegexTest_200")
                << QLatin1StringView("RegexTest_201")
                << QLatin1StringView("RegexTest_201")
                << QLatin1StringView("RegexTest_202")
                << QLatin1StringView("RegexTest_202")
                << QLatin1StringView("RegexTest_203")
                << QLatin1StringView("RegexTest_204")
                << QLatin1StringView("RegexTest_205")
                << QLatin1StringView("RegexTest_206")
                << QLatin1StringView("RegexTest_207")
                << QLatin1StringView("RegexTest_208")
                << QLatin1StringView("RegexTest_209")
                << QLatin1StringView("RegexTest_209")
                << QLatin1StringView("RegexTest_210")
                << QLatin1StringView("RegexTest_210")
                << QLatin1StringView("RegexTest_211")
                << QLatin1StringView("RegexTest_211")
                << QLatin1StringView("RegexTest_212")
                << QLatin1StringView("RegexTest_213")
                << QLatin1StringView("RegexTest_214")
                << QLatin1StringView("RegexTest_215")
                << QLatin1StringView("RegexTest_216")
                << QLatin1StringView("RegexTest_217")
                << QLatin1StringView("RegexTest_218")
                << QLatin1StringView("RegexTest_220")
                << QLatin1StringView("RegexTest_221")
                << QLatin1StringView("RegexTest_222")
                << QLatin1StringView("RegexTest_226")
                << QLatin1StringView("RegexTest_230")
                << QLatin1StringView("RegexTest_232")
                << QLatin1StringView("RegexTest_233")
                << QLatin1StringView("RegexTest_294")
                << QLatin1StringView("RegexTest_294")
                << QLatin1StringView("RegexTest_295")
                << QLatin1StringView("RegexTest_295")
                << QLatin1StringView("RegexTest_299")
                << QLatin1StringView("RegexTest_300")
                << QLatin1StringView("RegexTest_301")
                << QLatin1StringView("RegexTest_302")
                << QLatin1StringView("RegexTest_303")
                << QLatin1StringView("RegexTest_304")
                << QLatin1StringView("RegexTest_305")
                << QLatin1StringView("RegexTest_306")
                << QLatin1StringView("RegexTest_307")
                << QLatin1StringView("RegexTest_308")
                << QLatin1StringView("RegexTest_309")
                << QLatin1StringView("RegexTest_310")
                << QLatin1StringView("RegexTest_311")
                << QLatin1StringView("RegexTest_312")
                << QLatin1StringView("RegexTest_313")
                << QLatin1StringView("RegexTest_314")
                << QLatin1StringView("RegexTest_315")
                << QLatin1StringView("RegexTest_315")
                << QLatin1StringView("RegexTest_316")
                << QLatin1StringView("RegexTest_316")
                << QLatin1StringView("RegexTest_317")
                << QLatin1StringView("RegexTest_317")
                << QLatin1StringView("RegexTest_440")
                << QLatin1StringView("RegexTest_441")
                << QLatin1StringView("RegexTest_442")
                << QLatin1StringView("RegexTest_443")
                << QLatin1StringView("RegexTest_448")
                << QLatin1StringView("RegexTest_449")
                << QLatin1StringView("RegexTest_450")
                << QLatin1StringView("RegexTest_451")
                << QLatin1StringView("RegexTest_458")
                << QLatin1StringView("RegexTest_464")
                << QLatin1StringView("RegexTest_464")
                << QLatin1StringView("RegexTest_465")
                << QLatin1StringView("RegexTest_469")
                << QLatin1StringView("RegexTest_470")
                << QLatin1StringView("RegexTest_471")
                << QLatin1StringView("RegexTest_472")
                << QLatin1StringView("RegexTest_473")
                << QLatin1StringView("RegexTest_477")
                << QLatin1StringView("RegexTest_478")
                << QLatin1StringView("RegexTest_478")
                << QLatin1StringView("RegexTest_479")
                << QLatin1StringView("RegexTest_480")
                << QLatin1StringView("RegexTest_481")
                << QLatin1StringView("RegexTest_482")
                << QLatin1StringView("RegexTest_482")
                << QLatin1StringView("RegexTest_483")
                << QLatin1StringView("RegexTest_483")
                << QLatin1StringView("RegexTest_484")
                << QLatin1StringView("RegexTest_487")
                << QLatin1StringView("RegexTest_516")
                << QLatin1StringView("RegexTest_516")
                << QLatin1StringView("RegexTest_517")
                << QLatin1StringView("RegexTest_517")
                << QLatin1StringView("RegexTest_518")
                << QLatin1StringView("RegexTest_518")
                << QLatin1StringView("RegexTest_519")
                << QLatin1StringView("RegexTest_519")
                << QLatin1StringView("RegexTest_521")
                << QLatin1StringView("RegexTest_523")
                << QLatin1StringView("RegexTest_524")
                << QLatin1StringView("RegexTest_524")
                << QLatin1StringView("RegexTest_586")
                << QLatin1StringView("RegexTest_587")
                << QLatin1StringView("RegexTest_592")
                << QLatin1StringView("RegexTest_593")
                << QLatin1StringView("RegexTest_594")
                << QLatin1StringView("RegexTest_595")
                << QLatin1StringView("RegexTest_596")
                << QLatin1StringView("RegexTest_597")
                << QLatin1StringView("RegexTest_598")
                << QLatin1StringView("RegexTest_599")
                << QLatin1StringView("RegexTest_600")
                << QLatin1StringView("RegexTest_601")
                << QLatin1StringView("RegexTest_602")
                << QLatin1StringView("RegexTest_603")
                << QLatin1StringView("RegexTest_604")
                << QLatin1StringView("RegexTest_605")
                << QLatin1StringView("RegexTest_648")
                << QLatin1StringView("RegexTest_655")
                << QLatin1StringView("RegexTest_688")
                << QLatin1StringView("RegexTest_696")
                << QLatin1StringView("RegexTest_697")
                << QLatin1StringView("RegexTest_698")
                << QLatin1StringView("RegexTest_700")
                << QLatin1StringView("RegexTest_701")
                << QLatin1StringView("RegexTest_702")
                << QLatin1StringView("RegexTest_703")
                << QLatin1StringView("RegexTest_704")
                << QLatin1StringView("RegexTest_705")
                << QLatin1StringView("RegexTest_706")
                << QLatin1StringView("RegexTest_707")
                << QLatin1StringView("RegexTest_717")
                << QLatin1StringView("RegexTest_718")
                << QLatin1StringView("RegexTest_719")
                << QLatin1StringView("RegexTest_724")
                << QLatin1StringView("RegexTest_725")
                << QLatin1StringView("RegexTest_726")
                << QLatin1StringView("RegexTest_727")
                << QLatin1StringView("RegexTest_728")
                << QLatin1StringView("RegexTest_729")
                << QLatin1StringView("RegexTest_730")
                << QLatin1StringView("RegexTest_731")
                << QLatin1StringView("RegexTest_732")
                << QLatin1StringView("RegexTest_733")
                << QLatin1StringView("RegexTest_743")
                << QLatin1StringView("RegexTest_755")
                << QLatin1StringView("RegexTest_756")
                << QLatin1StringView("RegexTest_761")
                << QLatin1StringView("RegexTest_762")
                << QLatin1StringView("RegexTest_781")
                << QLatin1StringView("RegexTest_782")
                << QLatin1StringView("RegexTest_783")
                << QLatin1StringView("RegexTest_790")
                << QLatin1StringView("RegexTest_791")
                << QLatin1StringView("RegexTest_824")
                << QLatin1StringView("RegexTest_826")
                << QLatin1StringView("RegexTest_827")
                << QLatin1StringView("RegexTest_836")
                << QLatin1StringView("RegexTest_837")
                << QLatin1StringView("RegexTest_841")
                << QLatin1StringView("RegexTest_842")
                << QLatin1StringView("RegexTest_843")
                << QLatin1StringView("RegexTest_844")
                << QLatin1StringView("RegexTest_845")
                << QLatin1StringView("RegexTest_846")
                << QLatin1StringView("RegexTest_847")
                << QLatin1StringView("RegexTest_848")
                << QLatin1StringView("RegexTest_851")
                << QLatin1StringView("RegexTest_852")
                << QLatin1StringView("RegexTest_853")
                << QLatin1StringView("RegexTest_854")
                << QLatin1StringView("RegexTest_855")
                << QLatin1StringView("RegexTest_856")
                << QLatin1StringView("RegexTest_857")
                << QLatin1StringView("RegexTest_861")
                << QLatin1StringView("RegexTest_862")
                << QLatin1StringView("RegexTest_863")
                << QLatin1StringView("RegexTest_864")
                << QLatin1StringView("RegexTest_865")
                << QLatin1StringView("RegexTest_866")
                << QLatin1StringView("RegexTest_870")
                << QLatin1StringView("RegexTest_879")
                << QLatin1StringView("RegexTest_880")
                << QLatin1StringView("RegexTest_888")
                << QLatin1StringView("RegexTest_889")
                << QLatin1StringView("RegexTest_890")
                << QLatin1StringView("RegexTest_891")
                << QLatin1StringView("RegexTest_892")
                << QLatin1StringView("RegexTest_893")
                << QLatin1StringView("RegexTest_894")
                << QLatin1StringView("RegexTest_895")
                << QLatin1StringView("RegexTest_896")
                << QLatin1StringView("RegexTest_897")
                << QLatin1StringView("RegexTest_898")
                << QLatin1StringView("RegexTest_899")
                << QLatin1StringView("RegexTest_900")
                << QLatin1StringView("RegexTest_901")
                << QLatin1StringView("RegexTest_902")
                << QLatin1StringView("RegexTest_903")
                << QLatin1StringView("RegexTest_904")
                << QLatin1StringView("RegexTest_905")
                << QLatin1StringView("RegexTest_906")
                << QLatin1StringView("RegexTest_907")
                << QLatin1StringView("RegexTest_908")
                << QLatin1StringView("RegexTest_909")
                << QLatin1StringView("RegexTest_910")
                << QLatin1StringView("RegexTest_911")
                << QLatin1StringView("RegexTest_912")
                << QLatin1StringView("RegexTest_913")
                << QLatin1StringView("RegexTest_914")
                << QLatin1StringView("RegexTest_915")
                << QLatin1StringView("RegexTest_916")
                << QLatin1StringView("RegexTest_917")
                << QLatin1StringView("RegexTest_918")
                << QLatin1StringView("RegexTest_919")
                << QLatin1StringView("RegexTest_920")
                << QLatin1StringView("RegexTest_921")
                << QLatin1StringView("RegexTest_922")
                << QLatin1StringView("RegexTest_923")
                << QLatin1StringView("RegexTest_924")
                << QLatin1StringView("RegexTest_925")
                << QLatin1StringView("RegexTest_926")
                << QLatin1StringView("RegexTest_928")
                << QLatin1StringView("RegexTest_929")
                << QLatin1StringView("RegexTest_930")
                << QLatin1StringView("RegexTest_936")
                << QLatin1StringView("RegexTest_937")
                << QLatin1StringView("RegexTest_938")
                << QLatin1StringView("RegexTest_939")
                << QLatin1StringView("RegexTest_940")
                << QLatin1StringView("RegexTest_941")
                << QLatin1StringView("RegexTest_942")
                << QLatin1StringView("RegexTest_943")
                << QLatin1StringView("RegexTest_944")
                << QLatin1StringView("RegexTest_945")
                << QLatin1StringView("RegexTest_946")
                << QLatin1StringView("RegexTest_949")
                << QLatin1StringView("RegexTest_950")
                << QLatin1StringView("RegexTest_951")
                << QLatin1StringView("RegexTest_952")
                << QLatin1StringView("RegexTest_953")
                << QLatin1StringView("RegexTest_954")
                << QLatin1StringView("RegexTest_955")
                << QLatin1StringView("RegexTest_956")
                << QLatin1StringView("RegexTest_957")
                << QLatin1StringView("RegexTest_958")
                << QLatin1StringView("RegexTest_959")
                << QLatin1StringView("RegexTest_960")
                << QLatin1StringView("RegexTest_961")
                << QLatin1StringView("RegexTest_962")
                << QLatin1StringView("RegexTest_963")
                << QLatin1StringView("RegexTest_964")
                << QLatin1StringView("RegexTest_976")
                << QLatin1StringView("RegexTest_977")
                << QLatin1StringView("RegexTest_988")
                << QLatin1StringView("RegexTest_989")
                << QLatin1StringView("RegexTest_990")
                << QLatin1StringView("RegexTest_991")
                << QLatin1StringView("RegexTest_994")
                << QLatin1StringView("RegexTest_995")
                << QLatin1StringView("RegexTest_996")
                << QLatin1StringView("RegexTest_997")
                << QLatin1StringView("RegexTest_1000")
                << QLatin1StringView("RegexTest_1001")
                << QLatin1StringView("RegexTest_1002")
                << QLatin1StringView("RegexTest_1003")
                << QLatin1StringView("RegexTest_1004")
                << QLatin1StringView("RegexTest_1007")
                << QLatin1StringView("RegexTest_1008")
                << QLatin1StringView("RegexTest_1009")
                << QLatin1StringView("RegexTest_1010")
                << QLatin1StringView("RegexTest_1011")
                << QLatin1StringView("RegexTest_1012")
                << QLatin1StringView("RegexTest_1013")
                << QLatin1StringView("RegexTest_1014")
                << QLatin1StringView("RegexTest_1015")
                << QLatin1StringView("RegexTest_1016")
                << QLatin1StringView("RegexTest_1017")
                << QLatin1StringView("RegexTest_1018")
                << QLatin1StringView("RegexTest_1019")
                << QLatin1StringView("RegexTest_1070")
                << QLatin1StringView("RegexTest_1071")
                << QLatin1StringView("RegexTest_1076")
                << QLatin1StringView("RegexTest_1077")
                << QLatin1StringView("RegexTest_1078")
                << QLatin1StringView("RegexTest_1079")
                << QLatin1StringView("RegexTest_1080")
                << QLatin1StringView("RegexTest_1081")
                << QLatin1StringView("RegexTest_1082")
                << QLatin1StringView("RegexTest_1083")
                << QLatin1StringView("RegexTest_1084")
                << QLatin1StringView("RegexTest_1085")
                << QLatin1StringView("RegexTest_1086")
                << QLatin1StringView("RegexTest_1087")
                << QLatin1StringView("RegexTest_1088")
                << QLatin1StringView("RegexTest_1089")
                << QLatin1StringView("RegexTest_1132")
                << QLatin1StringView("RegexTest_1139")
                << QLatin1StringView("RegexTest_1172")
                << QLatin1StringView("RegexTest_1180")
                << QLatin1StringView("RegexTest_1181")
                << QLatin1StringView("RegexTest_1182")
                << QLatin1StringView("RegexTest_1184")
                << QLatin1StringView("RegexTest_1185")
                << QLatin1StringView("RegexTest_1186")
                << QLatin1StringView("RegexTest_1187")
                << QLatin1StringView("RegexTest_1188")
                << QLatin1StringView("RegexTest_1189")
                << QLatin1StringView("RegexTest_1190")
                << QLatin1StringView("RegexTest_1191")
                << QLatin1StringView("RegexTest_1201")
                << QLatin1StringView("RegexTest_1202")
                << QLatin1StringView("RegexTest_1203")
                << QLatin1StringView("RegexTest_1208")
                << QLatin1StringView("RegexTest_1209")
                << QLatin1StringView("RegexTest_1210")
                << QLatin1StringView("RegexTest_1211")
                << QLatin1StringView("RegexTest_1212")
                << QLatin1StringView("RegexTest_1213")
                << QLatin1StringView("RegexTest_1214")
                << QLatin1StringView("RegexTest_1215")
                << QLatin1StringView("RegexTest_1216")
                << QLatin1StringView("RegexTest_1217")
                << QLatin1StringView("RegexTest_1227")
                << QLatin1StringView("RegexTest_1239")
                << QLatin1StringView("RegexTest_1240")
                << QLatin1StringView("RegexTest_1245")
                << QLatin1StringView("RegexTest_1246")
                << QLatin1StringView("RegexTest_1265")
                << QLatin1StringView("RegexTest_1266")
                << QLatin1StringView("RegexTest_1267")
                << QLatin1StringView("RegexTest_1274")
                << QLatin1StringView("RegexTest_1275")
                << QLatin1StringView("RegexTest_1308")
                << QLatin1StringView("RegexTest_1310")
                << QLatin1StringView("RegexTest_1311")
                << QLatin1StringView("RegexTest_1320")
                << QLatin1StringView("RegexTest_1321")
                << QLatin1StringView("RegexTest_1322")
                << QLatin1StringView("RegexTest_1323")
                << QLatin1StringView("RegexTest_1324")
                << QLatin1StringView("RegexTest_1325")
                << QLatin1StringView("RegexTest_1326")
                << QLatin1StringView("RegexTest_1327")
                << QLatin1StringView("RegexTest_1328")
                << QLatin1StringView("RegexTest_1329")
                << QLatin1StringView("RegexTest_1330")
                << QLatin1StringView("RegexTest_1331")
                << QLatin1StringView("RegexTest_1332")
                << QLatin1StringView("RegexTest_1335")
                << QLatin1StringView("RegexTest_1336")
                << QLatin1StringView("RegexTest_1337")
                << QLatin1StringView("RegexTest_1338")
                << QLatin1StringView("RegexTest_1339")
                << QLatin1StringView("RegexTest_1340")
                << QLatin1StringView("RegexTest_1341")
                << QLatin1StringView("RegexTest_1345")
                << QLatin1StringView("RegexTest_1346")
                << QLatin1StringView("RegexTest_1347")
                << QLatin1StringView("RegexTest_1348")
                << QLatin1StringView("RegexTest_1349")
                << QLatin1StringView("RegexTest_1350")
                << QLatin1StringView("RegexTest_1354")
                << QLatin1StringView("RegexTest_1363")
                << QLatin1StringView("RegexTest_1364")
                << QLatin1StringView("RegexTest_1365")
                << QLatin1StringView("RegexTest_1372")
                << QLatin1StringView("RegexTest_1373")
                << QLatin1StringView("RegexTest_1374")
                << QLatin1StringView("RegexTest_1375")
                << QLatin1StringView("RegexTest_1376")
                << QLatin1StringView("RegexTest_1377")
                << QLatin1StringView("RegexTest_1378")
                << QLatin1StringView("RegexTest_1379")
                << QLatin1StringView("RegexTest_1380")
                << QLatin1StringView("RegexTest_1381")
                << QLatin1StringView("RegexTest_1382")
                << QLatin1StringView("RegexTest_1383")
                << QLatin1StringView("RegexTest_1384")
                << QLatin1StringView("RegexTest_1385")
                << QLatin1StringView("RegexTest_1386")
                << QLatin1StringView("RegexTest_1387")
                << QLatin1StringView("RegexTest_1388")
                << QLatin1StringView("RegexTest_1389")
                << QLatin1StringView("RegexTest_1390")
                << QLatin1StringView("RegexTest_1391")
                << QLatin1StringView("RegexTest_1392")
                << QLatin1StringView("RegexTest_1393")
                << QLatin1StringView("RegexTest_1394")
                << QLatin1StringView("RegexTest_1395")
                << QLatin1StringView("RegexTest_1396")
                << QLatin1StringView("RegexTest_1397")
                << QLatin1StringView("RegexTest_1398")
                << QLatin1StringView("RegexTest_1399")
                << QLatin1StringView("RegexTest_1400")
                << QLatin1StringView("RegexTest_1401")
                << QLatin1StringView("RegexTest_1402")
                << QLatin1StringView("RegexTest_1403")
                << QLatin1StringView("RegexTest_1404")
                << QLatin1StringView("RegexTest_1405")
                << QLatin1StringView("RegexTest_1406")
                << QLatin1StringView("RegexTest_1407")
                << QLatin1StringView("RegexTest_1408")
                << QLatin1StringView("RegexTest_1409")
                << QLatin1StringView("RegexTest_1410")
                << QLatin1StringView("RegexTest_1412")
                << QLatin1StringView("RegexTest_1413")
                << QLatin1StringView("RegexTest_1414")
                << QLatin1StringView("RegexTest_1420")
                << QLatin1StringView("RegexTest_1421")
                << QLatin1StringView("RegexTest_1422")
                << QLatin1StringView("RegexTest_1423")
                << QLatin1StringView("RegexTest_1424")
                << QLatin1StringView("RegexTest_1425")
                << QLatin1StringView("RegexTest_1426")
                << QLatin1StringView("RegexTest_1427")
                << QLatin1StringView("RegexTest_1428")
                << QLatin1StringView("RegexTest_1429")
                << QLatin1StringView("RegexTest_1430")
                << QLatin1StringView("RegexTest_1433")
                << QLatin1StringView("RegexTest_1434")
                << QLatin1StringView("RegexTest_1435")
                << QLatin1StringView("RegexTest_1436")
                << QLatin1StringView("RegexTest_1437")
                << QLatin1StringView("RegexTest_1438")
                << QLatin1StringView("RegexTest_1439")
                << QLatin1StringView("RegexTest_1440")
                << QLatin1StringView("RegexTest_1441")
                << QLatin1StringView("RegexTest_1442")
                << QLatin1StringView("RegexTest_1443")
                << QLatin1StringView("RegexTest_1444")
                << QLatin1StringView("RegexTest_1445")
                << QLatin1StringView("RegexTest_1446")
                << QLatin1StringView("RegexTest_1447")
                << QLatin1StringView("RegexTest_1448")
                << QLatin1StringView("RegexTest_1451")
                << QLatin1StringView("RegexTest_1452")
                << QLatin1StringView("RegexTest_1453")
                << QLatin1StringView("RegexTest_1454")
                << QLatin1StringView("RegexTest_1455")
                << QLatin1StringView("RegexTest_1456")
                << QLatin1StringView("RegexTest_1472")
                << QLatin1StringView("RegexTest_1473")
                << QLatin1StringView("RegexTest_1474")
                << QLatin1StringView("RegexTest_1475")
                << QLatin1StringView("RegexTest_1478")
                << QLatin1StringView("RegexTest_1479")
                << QLatin1StringView("RegexTest_1480")
                << QLatin1StringView("RegexTest_1481")
                << QLatin1StringView("RegexTest_1484")
                << QLatin1StringView("RegexTest_1485")
                << QLatin1StringView("RegexTest_1486")
                << QLatin1StringView("RegexTest_1487")
                << QLatin1StringView("RegexTest_1488")
                << QLatin1StringView("RegexTest_1491")
                << QLatin1StringView("RegexTest_1492")
                << QLatin1StringView("RegexTest_1493")
                << QLatin1StringView("RegexTest_1494")
                << QLatin1StringView("RegexTest_1495")
                << QLatin1StringView("RegexTest_1496")
                << QLatin1StringView("RegexTest_1497")
                << QLatin1StringView("RegexTest_1498")
                << QLatin1StringView("RegexTest_1499")
                << QLatin1StringView("RegexTest_1500")
                << QLatin1StringView("RegexTest_1501")
                << QLatin1StringView("RegexTest_1502")
                << QLatin1StringView("RegexTest_1503")
                << QLatin1StringView("RegexTest_1543")
                << QLatin1StringView("RegexTest_1544")
                << QLatin1StringView("reZ001")
*/
                << QLatin1StringView("schA2")
                << QLatin1StringView("schA5")
                << QLatin1StringView("schA7")
                << QLatin1StringView("schD8")
                << QLatin1StringView("schG3")
                << QLatin1StringView("schG6")
                << QLatin1StringView("schG9")
                << QLatin1StringView("schG11")
                << QLatin1StringView("schG12")
                << QLatin1StringView("schU1")
                << QLatin1StringView("schU3")
                << QLatin1StringView("schU4")
                << QLatin1StringView("schU5")
                << QLatin1StringView("schZ004")
                << QLatin1StringView("schZ005")
                << QLatin1StringView("schZ012_a")
                << QLatin1StringView("stZ041")
                << QLatin1StringView("wildZ010");
}

bool XSDTestSuiteHandler::startElement(const QStringRef &namespaceURI, const QStringRef &localName,
                                       const QStringRef & /*qName*/, const QXmlStreamAttributes &atts)
{
    if(namespaceURI != QString::fromLatin1("http://www.w3.org/XML/2004/xml-schema-test-suite/"))
        return true;

    if (localName == QLatin1StringView("testSet")) {
        m_currentTestSet = new TestGroup(m_topLevelGroup);
        Q_ASSERT(m_currentTestSet);
        m_currentTestSet->setTitle(atts.value("name").toString());
        m_topLevelGroup->appendChild(m_currentTestSet);
    } else if (localName == QLatin1StringView("testGroup")) {
        m_currentTestGroup = new TestGroup(m_currentTestSet);
        Q_ASSERT(m_currentTestGroup);
        m_currentTestGroup->setTitle(atts.value("name").toString());
        m_currentTestSet->appendChild(m_currentTestGroup);
        m_inTestGroup = true;
    } else if (localName == QLatin1StringView("schemaTest")) {
        if (m_blackList.contains(atts.value("name").toString())) {
            m_currentTestCase = 0;
            m_schemaBlacklisted = true;
            return true;
        }
        m_schemaBlacklisted = false;

        m_currentTestCase = new XSDTSTestCase(TestCase::Standard, m_currentTestGroup, XSDTSTestCase::SchemaTest);
        Q_ASSERT(m_currentTestCase);
        m_counter++;
        m_currentTestCase->setName(QString::number(m_counter) + atts.value("name"));
        m_currentTestGroup->appendChild(m_currentTestCase);
        m_currentTestCase->setParent(m_currentTestGroup);

        m_inSchemaTest = true;
    } else if (localName == QLatin1StringView("instanceTest")) {
        if (m_schemaBlacklisted) {
            m_currentTestCase = 0;
            return true;
        }

        m_currentTestCase = new XSDTSTestCase(TestCase::Standard, m_currentTestGroup, XSDTSTestCase::InstanceTest);
        Q_ASSERT(m_currentTestCase);
        m_counter++;
        m_currentTestCase->setName(QString::number(m_counter) + atts.value("name"));
        m_currentTestGroup->appendChild(m_currentTestCase);

        m_inInstanceTest = true;
    } else if (localName == QLatin1StringView("schemaDocument") || localName == QLatin1StringView("instanceDocument")) {
        if (m_inSchemaTest) {
            m_currentTestCase->setSchemaUri(QUrl(atts.value("xlink:href").toString()));
            if (m_currentSchemaLink.isEmpty()) // we only use the first schema document for validation
                m_currentSchemaLink = atts.value("xlink:href").toString();
        }
        if (m_inInstanceTest) {
            m_currentTestCase->setInstanceUri(QUrl(atts.value("xlink:href").toString()));
            m_currentTestCase->setSchemaUri(QUrl(m_currentSchemaLink));
        }
    } else if (localName == QLatin1StringView("expected") && (m_inSchemaTest || m_inInstanceTest)) {
        TestBaseLine *baseLine = new TestBaseLine(TestBaseLine::SchemaIsValid);
        if (atts.value("validity") == QLatin1StringView("valid")) {
            baseLine->setDetails(QLatin1StringView("true"));
            m_currentTestCase->setName(m_currentTestCase->name() + QLatin1StringView(" tokoe:valid"));
        } else {
            baseLine->setDetails(QLatin1StringView("false"));
            m_currentTestCase->setName(m_currentTestCase->name() + QLatin1StringView(" tokoe:invalid"));
        }

        m_currentTestCase->addBaseLine(baseLine);
    } else if (localName == QLatin1StringView("documentation") && m_inTestGroup) {
        m_inDescription = true;
    }

    return true;
}

bool XSDTestSuiteHandler::endElement(const QStringRef &/*namespaceURI*/,
                                      const QStringRef &localName,
                                      const QStringRef &/*qName*/)
{
    if (localName == QLatin1StringView("testGroup")) {
        m_inTestGroup = false;
        m_currentTestGroup->setDescription(m_documentation);
        m_documentation.clear();
        m_currentSchemaLink.clear();

        if (m_currentTestGroup->childCount() == 0)
            m_currentTestSet->removeLast();
    } else if (localName == QLatin1StringView("schemaTest"))
        m_inSchemaTest = false;
    else if (localName == QLatin1StringView("instanceTest"))
        m_inInstanceTest = false;
    else if (localName == QLatin1StringView("documentation"))
        m_inDescription = false;

    return true;
}

bool XSDTestSuiteHandler::characters(const QStringRef &ch)
{
    if (m_inDescription)
        m_documentation += ch;

    return true;
}

TestSuite *XSDTestSuiteHandler::testSuite() const
{
    return m_ts;
}

// vim: et:ts=4:sw=4:sts=4

